apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - port: 9999
      targetPort: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx:1.21.5-alpine
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
